include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    discarded_futures: true
    unawaited_futures: true
    prefer_initializing_formals: false
    use_null_aware_elements: false
