// GENERATED CODE - DO NOT MODIFY BY HAND.
// Obfuscation is anti-grep only, not security.
part of 'routes.dart';

const _encodedRouteValues = <String, String>{
  "prefix": "L2FwaS9leHRlcm5hbC92MQ==",
  "usersApiPrefix": "L2FwaS92MQ==",
  "health": "L2hlYWx0aA==",
  "searchClient": "L3NlYXJjaA==",
  "groups": "L2NvbGxlY3Rpb24vZ3JvdXBz",
  "indexationJobs": "L2luZGV4YXRpb24vam9icw==",
  "indexationSubmit": "L2luZGV4YXRpb24vam9iL2NyZWF0ZQ==",
  "indexationStatus": "L2luZGV4YXRpb24vam9iL3tqb2JfaWR9",
  "indexationDelete": "L2luZGV4YXRpb24vaW5kZXgvZGVsZXRl",
  "upload": "L2NvbGxlY3Rpb24vdXBsb2Fk",
  "uploadFolder": "L3VwbG9hZC9mb2xkZXI=",
  "uploadGoogleDriveFolder": "L2NvbGxlY3Rpb24vdXBsb2FkL2dvb2dsZV9kcml2ZQ==",
  "uploadMetadataJsonl": "L2NvbGxlY3Rpb24vdXBsb2FkL21ldGFkYXRh",
  "collectionDescriptionUpdate": "L2NvbGxlY3Rpb24vZGVzY3JpcHRpb24vdXBkYXRl",
  "collectionDelete": "L2NvbGxlY3Rpb24vZGVsZXRl",
  "collectionAddAssets":
      "L2NvbGxlY3Rpb24ve2NvbGxlY3Rpb25faWR9L2Fzc2V0cy9jcmVhdGU=",
  "adminUserStats": "L2FkbWluL3VzZXItc3RhdHM=",
  "uploadMetadataItemParquetInternal":
      "L2FwaS9pbnRlcm5hbC92MS9jb2xsZWN0aW9uL3VwbG9hZC9tZXRhZGF0YQ==",
  "imageGetUrl": "L2ltYWdlL2dldF91cmw=",
  "imageGetUrlBulk": "L2ltYWdlL2dldF91cmxfYnVsaw==",
  "imageGetImage": "L2ltYWdlL2dldF9pbWFnZQ==",
  "imageGetImageBulk": "L2ltYWdlL2dldF9pbWFnZV9idWxr",
  "authMe": "L2F1dGgvbWU=",
  "adminUsage": "L2FkbWluL3VzYWdl",
  "adminCacheStats": "L2FkbWluL2NhY2hlL3N0YXRz",
  "r2Credentials": "L2dldF9yMl9jcmVkZW50aWFscy8=",
  "r2UploadFile": "L3VwbG9hZF9maWxlLw==",
  "r2UploadFolderVideo": "L3VwbG9hZF9mb2xkZXJfdmlkZW8v",
  "externalUploadGetSignedUrl":
      "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9nZXRfc2lnbmVkX3VybA==",
  "externalUploadDone": "L2NvbGxlY3Rpb24vdXBsb2FkL2RvbmU=",
  "externalUploadMultipartCreate":
      "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvY3JlYXRl",
  "externalUploadMultipartSignParts":
      "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvc2lnbl9wYXJ0cw==",
  "externalUploadMultipartStatus":
      "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvc3RhdHVz",
  "externalUploadMultipartComplete":
      "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvY29tcGxldGU=",
  "externalUploadMultipartAbort":
      "L2NvbGxlY3Rpb25zL2V4dGVybmFsX3VwbG9hZF9tdWx0aXBhcnQvYWJvcnQ=",
  "embeddingModels": "L2luZGV4ZXMvZW1iZWRkaW5nX21vZGVscw==",
  "autoIndex": "L2NvbGxlY3Rpb24vYXV0b19pbmRleA==",
  "gdrivePrivateAuthUrl": "L2dkcml2ZS9wcml2YXRlL2F1dGgtdXJs",
  "gdrivePrivateDownload": "L2dkcml2ZS9wcml2YXRlL2ZvbGRlci9kb3dubG9hZA==",
  "sqlQuery": "L3NxbC9xdWVyeQ==",
  "empty": "",
};

final _decodedRouteValues = <String, String>{};

String _routeValue(String key) => _decodedRouteValues.putIfAbsent(
  key,
  () => utf8.decode(base64Decode(_encodedRouteValues[key]!)),
);

List<RouteSpec>? _routeSpecsCache;

List<RouteSpec> get _routeSpecs => _routeSpecsCache ??= <RouteSpec>[
  RouteSpec(
    "auth.health",
    "GET",
    _routeValue("health"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "auth.auth_check",
    "GET",
    _routeValue("health"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "searches.search_video",
    "POST",
    _routeValue("searchClient"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "collections.list_groups",
    "GET",
    _routeValue("groups"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "collections.upload_file",
    "POST",
    _routeValue("upload"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "collections.upload_metadata_jsonl",
    "POST",
    _routeValue("uploadMetadataJsonl"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "collections.update_description",
    "POST",
    _routeValue("collectionDescriptionUpdate"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "collections.delete",
    "DELETE",
    _routeValue("collectionDelete"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "collections.add_assets",
    "POST",
    _routeValue("collectionAddAssets"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "indexes.jobs_list",
    "GET",
    _routeValue("indexationJobs"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "indexes.create_index",
    "POST",
    _routeValue("indexationSubmit"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "indexes.index_status",
    "GET",
    _routeValue("indexationStatus"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "indexes.delete_index",
    "DELETE",
    _routeValue("indexationDelete"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "admin.user_stats",
    "GET",
    _routeValue("adminUserStats"),
    RouteCategory.active,
    "upstream",
  ),
  RouteSpec(
    "collections.upload_google_drive_folder",
    "POST",
    _routeValue("uploadGoogleDriveFolder"),
    RouteCategory.deprecated,
    "upstream",
  ),
  RouteSpec(
    "collections.upload_folder",
    "POST",
    _routeValue("uploadFolder"),
    RouteCategory.disabled,
    "upstream",
  ),
  RouteSpec(
    "indexes.embedding_models",
    "GET",
    _routeValue("embeddingModels"),
    RouteCategory.disabled,
    "upstream",
  ),
  RouteSpec(
    "collections.auto_index_get",
    "GET",
    _routeValue("autoIndex"),
    RouteCategory.disabled,
    "upstream",
  ),
  RouteSpec(
    "collections.auto_index_set",
    "POST",
    _routeValue("autoIndex"),
    RouteCategory.disabled,
    "upstream",
  ),
  RouteSpec(
    "gdrive.private_auth_url",
    "POST",
    _routeValue("gdrivePrivateAuthUrl"),
    RouteCategory.disabled,
    "upstream",
  ),
  RouteSpec(
    "gdrive.private_download",
    "POST",
    _routeValue("gdrivePrivateDownload"),
    RouteCategory.disabled,
    "upstream",
  ),
  RouteSpec(
    "sql.query",
    "POST",
    _routeValue("sqlQuery"),
    RouteCategory.disabled,
    "upstream",
  ),
  RouteSpec(
    "collections.create",
    "NONE",
    _routeValue("empty"),
    RouteCategory.disabled,
    "sdk_contract",
  ),
  RouteSpec(
    "collections.edit",
    "NONE",
    _routeValue("empty"),
    RouteCategory.disabled,
    "sdk_contract",
  ),
  RouteSpec(
    "images.get_url",
    "POST",
    _routeValue("imageGetUrl"),
    RouteCategory.image,
    "apionly_serve_img.py",
  ),
  RouteSpec(
    "images.get_url_bulk",
    "POST",
    _routeValue("imageGetUrlBulk"),
    RouteCategory.image,
    "apionly_serve_img.py",
  ),
  RouteSpec(
    "images.get_image_from_url",
    "POST",
    _routeValue("imageGetImage"),
    RouteCategory.image,
    "apionly_serve_img.py",
  ),
  RouteSpec(
    "images.get_image_bulk_from_urls",
    "POST",
    _routeValue("imageGetImageBulk"),
    RouteCategory.image,
    "apionly_serve_img.py",
  ),
  RouteSpec(
    "auth.me",
    "GET",
    _routeValue("authMe"),
    RouteCategory.usersApi,
    "users_api",
  ),
  RouteSpec(
    "admin.usage",
    "GET",
    _routeValue("adminUsage"),
    RouteCategory.usersApi,
    "users_api",
  ),
  RouteSpec(
    "admin.cache_stats",
    "GET",
    _routeValue("adminCacheStats"),
    RouteCategory.usersApi,
    "users_api",
  ),
  RouteSpec(
    "r2.credentials",
    "GET",
    _routeValue("r2Credentials"),
    RouteCategory.usersApi,
    "users_api",
  ),
  RouteSpec(
    "r2.presign_upload_file",
    "GET",
    _routeValue("r2UploadFile"),
    RouteCategory.usersApi,
    "users_api",
  ),
  RouteSpec(
    "r2.presign_upload_folder_video",
    "POST",
    _routeValue("r2UploadFolderVideo"),
    RouteCategory.usersApi,
    "users_api",
  ),
  RouteSpec(
    "collections.video_upload.presign",
    "POST",
    _routeValue("externalUploadGetSignedUrl"),
    RouteCategory.signedSingle,
    "sdk_python",
  ),
  RouteSpec(
    "collections.video_upload.done",
    "POST",
    _routeValue("externalUploadDone"),
    RouteCategory.signedSingle,
    "sdk_python",
  ),
  RouteSpec(
    "multipart.create",
    "POST",
    _routeValue("externalUploadMultipartCreate"),
    RouteCategory.multipartExperimental,
    "sdk_python",
  ),
  RouteSpec(
    "multipart.sign_parts",
    "POST",
    _routeValue("externalUploadMultipartSignParts"),
    RouteCategory.multipartExperimental,
    "sdk_python",
  ),
  RouteSpec(
    "multipart.status",
    "GET",
    _routeValue("externalUploadMultipartStatus"),
    RouteCategory.multipartExperimental,
    "sdk_python",
  ),
  RouteSpec(
    "multipart.complete",
    "POST",
    _routeValue("externalUploadMultipartComplete"),
    RouteCategory.multipartExperimental,
    "sdk_python",
  ),
  RouteSpec(
    "multipart.abort",
    "POST",
    _routeValue("externalUploadMultipartAbort"),
    RouteCategory.multipartExperimental,
    "sdk_python",
  ),
  RouteSpec(
    "metadata.internal_fallback",
    "POST",
    _routeValue("uploadMetadataItemParquetInternal"),
    RouteCategory.active,
    "sdk_python",
  ),
];
